### PR TITLE
Airport Outlier

### PR DESCRIPTION
**Pull request by arnoldbm**

### CODE REVIEW

**Comment by Broham** [comment]
@brock - It might be a good idea to add something to the read me that talks a bit about how this works and how to run it?

**Comment by brock** [comment]
Probably the wrong Brock. I'm guessing @arnoldbm

**Comment by Broham** [comment]
Yep - sorry @brock!

**Comment by Broham** [comment]
Awesome looks good @arnoldbm - I'll go ahead and merge unless you have any objections?

**Pull request merged**
